version: '3'

services:
  ui:
    build:
      context: ./ui
      dockerfile: ./Dockerfile
      args:
        ELM_APP_GRAPHQL_URI: localhost:8081/v1/graphql
        ELM_APP_CMD_URI: localhost:8080
    ports:
      - 3000:80
  cmd-api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_CONNECTION_STRING: postgres://postgres:secret@eventstore:5432/postgres
      PORT: "8080"  
  query-api:
    build:
      context: ./read-model
      dockerfile: ./Dockerfile
    environment:
      REDIS_URL: redis://redis:6379
      READ_MODEL: postgres://postgres:secret@read-model:5432/postgres
  eventstore:
    build: ./api/docker/eventstore
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: secret
  read-model-db:
    build: ./read-model/docker/read-model
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: secret
  pg-admin:
    image: dpage/pgadmin4
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: mail@example.com
      PGADMIN_DEFAULT_PASSWORD: secret      
  publisher:
    build:
      context: ./publisher
      dockerfile: ./Dockerfile
      args:
        REDIS_URL: redis://redis:6379
        DB_HOST: eventstore
        DB_NAME: postgres
        DB_USER: postgres
        DB_PASS: secret
  hasura:
    image: hasura/graphql-engine:v1.0.0-rc.1.cli-migrations
    ports:
      - 8081:8080
    volumes:
      - ./read-model/hasura:/hasura-migrations
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:secret@read-model-db:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      HASURA_GRAPHQL_ADMIN_SECRET: secret
    depends_on:
      - read-model-db
  redis:
    image: redis:5.0.7
    ports:
      - 6379:6379
