version: '2'

tasks:
  db:
    cmds:
      - docker-compose up -d read-model-db eventstore
      - sleep 5s # wait for 5 seconds to give the db enough time to start up
      - docker-compose up -d hasura

  cmd-api:
    dir: api
    cmds:
      - DB_CONNECTION_STRING="postgres://postgres:secret@localhost:5432/postgres" PORT="8080" stack run
      
  read-model:
    dir: read-model
    cmds:
      - task: db
      - READ_MODEL="postgres://postgres:secret@localhost:15432/postgres" EVENT_STORE="postgres://postgres:secret@localhost:5432/postgres" stack run

  ui:
    dir: ui
    cmds:
      - task start-local

  up:
    cmds:
      - docker-compose up -d read-model-db eventstore
      - sleep 5s # wait for 5 seconds to give the db enough time to start up
      - docker-compose up -d hasura
      - docker-compose up -d read-model cmd-api
      - docker-compose up -d ui

  down:
    cmds:
      - docker-compose down

  ps:
    cmds:
      - docker-compose ps
